### PR TITLE
Adding myself

### PR DESCRIPTION
**Pull request by markwhiting**
Just adding myself to the participants and projects yml files to reflect my participation in @iceLearn's (Dilrukshi Gamage's) project.

### CODE REVIEW

**Comment by abbycabs** [comment]
Thanks @markwhiting! 

This list reflects everyone registered in the program -- did you fill out the registration form? It was sent out to everyone list on the application earlier this month.

Thanks!

**Comment by markwhiting** [comment]
@acabunoc, my apologies. I've just filled it out.

**Comment by abbycabs** [comment]
Perfect, thanks @markwhiting!

**Comment by markwhiting** [comment]
Thanks! 

I just noticed that my profile image is not loading. It looks like the google drive link is to a file that is not publicly available perhaps.

**Pull request closed without merging**
